apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-12-16T08:28:00Z"
  generation: 1
  labels:
    app: mysql
  name: mysql
  namespace: coverage
  resourceVersion: "245409729"
  uid: cd0256ca-192d-4bd8-870b-e889516256ee
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - args:
        - mysqld
        - --early-plugin-load=keyring_file.so
        - --server-id=1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-init-credentials
        image: percona/percona-server:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: persistent-storage
          subPath: mysql
        - mountPath: /etc/my.cnf.d
          name: config-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1001:1001 /var/lib/mysql
        image: alpine:3.6
        imagePullPolicy: IfNotPresent
        name: set-key-ownership
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: persistent-storage
          subPath: mysql
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - configMap:
          defaultMode: 420
          name: mysql-config
          optional: true
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-12-16T08:28:00Z"
    lastUpdateTime: "2020-12-16T08:28:32Z"
    message: ReplicaSet "mysql-74dfb8679d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-07-08T17:48:46Z"
    lastUpdateTime: "2022-07-08T17:48:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
